### ISSUE TITLE
Feature Request: GitHub Actions Support

### ISSUE THREAD

**Issue by snaka** [fujiwara/tfstate-lookup#142]
It would be great to be able to install `tfstate-lookup` in the GitHub Actions workflow, as shown in the repo below.

https://github.com/cohalz/install-tfstate-lookup-action

Of course we can use `tfstate-lookup` by using the above, but it would be nice to have official support for it.

**Comment by snaka** [comment]
If the request is not needed for this repository, you can Close it.

Or, if you are willing to accept it, I can make a pull request. ;)

**Comment by fujiwara** [comment]
@snaka I'm sorry for the late response.

Maintaining actions for each tool repository incurs some costs for me. So, I recommend using "aqua" (https://github.com/aquaproj) to install tools in workflows. Aqua simplifies the installation and management of various tools.

**Comment by snaka** [comment]
Thanks for the good insight.

Well, I hadn't thought of using a version manager like Aqua for CI, but it certainly makes sense to use it.

I will close this issue.
