### ISSUE TITLE
tfstate-lookup ignores subscription_id in remote Azure backends

### ISSUE THREAD

**Issue by anorm** [fujiwara/tfstate-lookup#39]
When using a remote Azure backend and the storage account is located in a different subscription than what is currently selected using `az account set <id>`, tfstate-lookup fails with an error message like this:

> reading tfstate for azurerm_public_ip.primary.resource_group_name: failed to list keys: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'infrastructure-clickops' could not be found."

If I make sure to select the subscription where the storage account is before running tfstate-lookup, it works.

The `.tfstate` file contains the correct `subscription_id` so I suspect it's just about using this value and passing it along to the API.

I'm using tfstate-lookup through roboll/helmfile if that makes a difference :-)

**Comment by fujiwara** [comment]
@anorm Thank you!
Could you confirm this? https://github.com/fujiwara/tfstate-lookup/pull/45

**Comment by anorm** [comment]
Looks good :+1:

Failing on `master`:

```
❯ git checkout master
❯ go build -o tfstate-lookup cmd/tfstate-lookup/main.go
❯ az account set -s correct_subscription_id
❯ ./tfstate-lookup -s /path/to/terraform-project/.terraform/terraform.tfstate output.my_value
1
❯ az account set -s wrong_subscription_id
❯ ./tfstate-lookup -s /path/to/terraform-project/.terraform/terraform.tfstate output.my_value
failed to list keys: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'infrastructure-clickops' could not be found."
```

Working on 03caa87e374ae028a572b0ca5a2bee253d28f9f4:
```
❯ git checkout fix-azure-subsucription-id
❯ go build -o tfstate-lookup cmd/tfstate-lookup/main.go
❯ az account set -s correct_subscription_id
❯ ./tfstate-lookup -s /path/to/terraform-project/.terraform/terraform.tfstate output.my_value
1
❯ az account set -s wrong_subscription_id
❯ ./tfstate-lookup -s /path/to/terraform-project/.terraform/terraform.tfstate output.my_value
1
```
